# Generated by Django 5.0.7 on 2024-08-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='image',
        ),
        migrations.RemoveField(
            model_name='element',
            name='list',
        ),
        migrations.RemoveField(
            model_name='element',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='element',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='elements',
        ),
        migrations.RemoveField(
            model_name='list',
            name='items',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
        migrations.DeleteModel(
            name='SubTitle',
        ),
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.DeleteModel(
            name='ListItem',
        ),
    ]
