# Generated by Django 5.1 on 2024-08-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_popular',
            field=models.BooleanField(default=True),
        ),
    ]
