# Generated by Django 5.1 on 2024-08-27 01:26

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_is_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intro',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('posts', models.ManyToManyField(to='post.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
